move artifact to bin folder

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -47,6 +47,14 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-cabal-
 
+      - name: Debug Build Output
+        run: find dist-newstyle -type f -name "hasura" || echo "hasura not found"
+
+      - name: Move Binary to bin
+        run: |
+          mkdir -p bin
+          cp $(find dist-newstyle -type f -name "hasura" | head -n 1) bin/hasura
+
       - name: Update Cabal Version
         run: |
           ghcup install cabal 3.12
